### ISSUE TITLE
Create more edge case catches for sign in and sign up views

### ISSUE THREAD

**Issue by JacobMacFarland** [JacobMacFarland/HealthAndFitnessApplication#22]
Ex. We need to make sure the screen progressions cease if the necessary fields are not filled in during signup/sign-in process. This can be done by deleting the automatic link between views and creating a manual segue that only gets called in the proper portion of the if-else logic.

**Comment by sappqa** [comment]
We also need to consider checking a few other things on these screens
-Set a max number of characters for the username and password.
-Should we remove whitespace in usernames and passwords?
-Find other things we need to check for to make sure the input is valid. Ex. does the email address have an @ sign somewhere in it.
